name: ESLint

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x with Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.yarnpkg.com

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Lint with ESLint
        run: yarn run lint

      - name: Upload ESLint results
        uses: actions/upload-artifact@v2
