name: Test with Chat GPT API

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Test app
        env:
          REACT_APP_CHATGPT_API_KEY: ${{ CHATGPT_API_KEY.CHATGPT_API_KEY }}
        run: |
          yarn test

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
